martial_arts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('algo_task/', include('algo_task.urls'))
]

website/urls.py
from django.urls import path

from . import views

app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('price/', views.price, name='price'),
    path('instructor/', views.instructor, name='instructor'),
    path('timetable/', views.timetable, name='timetable'),
    path('review/', views.review, name='review')
]

#super commit

website/models.py
from django.db import models


# Create your models here.
class PriceModels(models.Model):
    description = models.CharField(max_length=225)
    number_of_trainings = models.IntegerField()
    cost = models.IntegerField()

    def __str__(self):
        return f"{self.id}&{self.description}"

    class Meta:
        verbose_name = "price"
        verbose_name_plural = "prices"
        ordering = ('number_of_trainings', 'cost')


class InstructorModels(models.Model):
    FIO = models.CharField(max_length=225)
    surname = models.CharField(max_length=225, unique=True)

    def __str__(self):
        return f"{self.id}&{self.FIO}"

    class Meta:
        verbose_name = "instructor"
        verbose_name_plural = "instructors"
        ordering = ('id',)


class UserModels(models.Model):
    surname = models.CharField(max_length=225)
    name = models.CharField(max_length=225)
    phone = models.CharField(max_length=13)
    email = models.EmailField(max_length=225)
    current_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id}&{self.surname}"

    class Meta:
        verbose_name = "user"
        verbose_name_plural = "users"
        ordering = ('id',)


class ReviewModels(models.Model):
    name = models.CharField(max_length=200)
    review = models.CharField(max_length=5000)
    current_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.id}&{self.name}"

    class Meta:
        verbose_name = "review"
        verbose_name_plural = "reviews"
        ordering = ('id',)


class TimetableModels(models.Model):
    instructor = models.ForeignKey(InstructorModels, on_delete=models.CASCADE, to_field='surname',
                                   db_column='instructor_surname')
    day = models.CharField(max_length=5)
    time_slot = models.CharField(max_length=15)
    direction = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.id}&{self.instructor_id}"

    class Meta:
        verbose_name = "timetable"
        verbose_name_plural = "timetable"
        ordering = ('time_slot',)


class InformationOfInstructorModels(models.Model):
    instructor = models.ForeignKey(InstructorModels, on_delete=models.CASCADE, to_field='surname',
                                   db_column='instructor_surname')
    type = models.CharField(max_length=225)
    information = models.CharField(max_length=300)

    def __str__(self):
        return f"{self.id}&{self.instructor}"

    class Meta:
        verbose_name = "information of instructor"
        verbose_name_plural = "information of instructors"
        ordering = ('id',)

website/views.py
from .models import PriceModels, InstructorModels, UserModels, ReviewModels
from .models import TimetableModels, InformationOfInstructorModels

from django.shortcuts import render, redirect


def index(request):
    if request.method == 'POST':
        surname = request.POST.get('last_name')
        name = request.POST.get('first_name')
        phone = request.POST.get('phone_number')
        email = request.POST.get('email')
        print(surname, name, phone, email)
        if surname and name and phone and email:
            UserModels.objects.create(surname=surname, name=name, phone=phone, email=email)
            return redirect('website:index')
        else:
            return redirect('website:index')
    return render(request, 'index.html')


def price(request):
    object = PriceModels.objects.all()
    print(object)
    context = []
    for i in range(len(object)):
        context.append(object.values('description', 'number_of_trainings', 'cost')[i])

    return render(request, 'price.html', {'context': context})


def instructor(request):
    instructors = InstructorModels.objects.all()
    context = []

    for instructor in instructors:
        information = InformationOfInstructorModels.objects.filter(instructor__surname=instructor.surname)
        grouped_info = {}

        for info in information:
            if info.type not in grouped_info:
                grouped_info[info.type] = []
            grouped_info[info.type].append(info.information)

        if 'Направления' in grouped_info:
            directions = grouped_info.pop('Направления')
            grouped_info = {'Направления': directions, **grouped_info}

        context.append({
            'instructor': instructor,
            'information': grouped_info
        })

    return render(request, 'instructor.html', {'context': context})


def timetable(request):
    timetable_data = []

    # Получаем все объекты TimetableModels из базы данных
    timetables = TimetableModels.objects.all()

    # Создаем словарь, который будет хранить данные расписания для каждого временного слота
    schedule_data = {}

    # Заполняем словарь schedule_data данными из модели TimetableModels
    for timetable in timetables:
        time_slot = timetable.time_slot
        day = timetable.day
        instructor = timetable.instructor
        direction = timetable.direction

        if time_slot not in schedule_data:
            schedule_data[time_slot] = {}

        schedule_data[time_slot][day] = {'instructor': instructor, 'direction': direction}

    # Получаем список временных слотов, отсортированных по времени
    time_slots = sorted(schedule_data.keys())

    # Получаем список дней недели
    days_of_week = ['Пн', 'Вт', 'Ср', 'Чт', 'Пт', 'Сб', 'Вс']

    # Создаем список словарей timetable_data для отображения в шаблоне
    for time_slot in time_slots:
        row_data = {'time_slot': time_slot}

        for day in days_of_week:
            instructor = schedule_data.get(time_slot, {}).get(day)
            row_data[day.lower() + '_instructor'] = instructor

        timetable_data.append(row_data)
    print(timetable_data)
    context = {'timetable_data': timetable_data}
    return render(request, 'timetable.html', context)


def review(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        review = request.POST.get('review')
        print(name, review)
        if name and review:
            ReviewModels.objects.create(name=name, review=review)
            return redirect('website:review')
        else:
            return redirect('website:review')
    return render(request, 'review.html')

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Школа боевых искусств</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="../static/main.css">
</head>
<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'website:index' %}">
            <span class="material-icons">sports_martial_arts</span>
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:price' %}">Цены</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:instructor' %}">Тренеры</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:timetable' %} ">Расписание</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'website:review' %} ">Отзывы</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="https://web.telegram.org/k/" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-telegram" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
                        </svg>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="https://www.instagram.com/" target="_blank">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                             class="bi bi-instagram" viewBox="0 0 16 16">
                            <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                        </svg>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

<div class="card text-white mb-4">
    <img src="../static/images/1HEXN7TK1v4.jpg" class="img-fluid dark-img" alt="" style="max-width: 100%;">
    <div class="card-img-overlay">
        <h5 class="display-6">Присоединяйтесь в команду <br> нашей школы боевых искусств <br> уже сегодня!</h5>
        <p class="lead">Приходи становиться сильнее!<br>
            Более 25 спортивных направлений для детей и взрослых.<br>
            Лучшие наставники уже ждут тебя.<br>
            Первая тренировка - БЕСПЛАТНО</p>
        <a href="#personalDataForm" class="btn btn-light btn-lg">Записаться на тренировку</a>
    </div>
</div>


<h2 class="display-6" style="text-align: center;">Хотите записаться на занятие - заполните форму и мы вам
    перезвоним</h2>
<div class="container mt-4">
    <form action="{% url 'website:index' %}" id="personalDataForm" method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label for="lastName" class="form-label">Фамилия</label>
            <input type="text" name="last_name" class="form-control" id="lastName" aria-describedby="lastNameHelp"
                   required>
            <div id="lastNameHelp" class="form-text">Введите фамилию с заглавной буквы</div>
        </div>
        <div class="mb-3">
            <label for="firstName" class="form-label">Имя</label>
            <input type="text" name="first_name" class="form-control" id="firstName" aria-describedby="firstNameHelp"
                   required>
            <div id="firstNameHelp" class="form-text">Введите имя с заглавной буквы</div>
        </div>
        <div class="mb-3">
            <label for="phoneNumber" class="form-label">Номер телефона</label>
            <input type="tel" name="phone_number" class="form-control" id="phoneNumber"
                   aria-describedby="phoneNumberHelp" required>
            <div id="phoneNumberHelp" class="form-text">Введите номер телефона</div>
        </div>
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" name="email" class="form-control" id="email" aria-describedby="emailHelp" required>
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <button type="submit" class="btn btn-dark">Отправить</button>
    </form>
</div>
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
        <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        </a>
        <span class="mb-3 mb-md-0 text-muted">© 2023 Company, Inc</span>
    </div>
    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
        <li class="ms-3">
            <a class="text-muted" href="https://web.telegram.org/k/">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-telegram" viewBox="0 0 16 16">
                    <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.287 5.906c-.778.324-2.334.994-4.666 2.01-.378.15-.577.298-.595.442-.03.243.275.339.69.47l.175.055c.408.133.958.288 1.243.294.26.006.549-.1.868-.32 2.179-1.471 3.304-2.214 3.374-2.23.05-.012.12-.026.166.016.047.041.042.12.037.141-.03.129-1.227 1.241-1.846 1.817-.193.18-.33.307-.358.336a8.154 8.154 0 0 1-.188.186c-.38.366-.664.64.015 1.088.327.216.589.393.85.571.284.194.568.387.936.629.093.06.183.125.27.187.331.236.63.448.997.414.214-.02.435-.22.547-.82.265-1.417.786-4.486.906-5.751a1.426 1.426 0 0 0-.013-.315.337.337 0 0 0-.114-.217.526.526 0 0 0-.31-.093c-.3.005-.763.166-2.984 1.09z"/>
                </svg>
            </a>
        </li>
        <li class="ms-3">
            <a class="text-muted" href="https://www.instagram.com/">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                     class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
                </svg>
            </a>
        </li>
    </ul>
</footer>
</body>
</html>