algo_task/urls.py
from django.urls import path

from . import views

app_name = 'algo_task'
urlpatterns = [
    path('', views.main, name='main'),
#    path('form_create_0/', views.form_create_0, name='form_create_0'),
    path('form_result/', views.form_result, name='form_result'),
    path('table/', views.table, name='table'),
]

martial_arts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('algo_task/', include('algo_task.urls'))
]

website/urls.py
from django.urls import path

from . import views

app_name = 'website'
urlpatterns = [
    path('', views.index, name='index'),
    path('price/', views.price, name='price'),
    path('instructor/', views.instructor, name='instructor'),
    path('timetable/', views.timetable, name='timetable'),
    path('review/', views.review, name='review')
]

#super commit

algo_task/models.py
from django.db import models


class AlgoTask(models.Model):
    task = models.CharField("Формулировка задачи",
                            default="1007. Имеются две ёмкости: кубическая с ребром A, цилиндрическая с высотой H и радиусом основания R. Определить, поместится ли жидкость объёма M в первую ёмкость, во вторую, в обе.",
                            max_length=255)
    A = models.IntegerField("Ребро куба", default=0, )
    H = models.IntegerField("Высота цилиндра", default=0, )
    R = models.IntegerField("Радиус цилиндра", default=0, )
    M = models.IntegerField("Обьем жидкости", default=0)
    current_date = models.DateTimeField("Дата изменения(save)", auto_now=True)

    def __str__(self):
        # return self.task
        # return '%s %s' % (self.task, self.current_date)
        return f"{self.id}&{self.task}"

    class Meta:
        verbose_name = "A_H_R_M"
        verbose_name_plural = "A_H_R_M_S"
        ordering = ('-id', '-M')

# python manage.py makemigrations
# python manage.py migrate

algo_task/forms.py
from django import forms
from django.forms import ModelForm
from .models import AlgoTask


class CreateAbcForm(ModelForm):
    # task = forms.CharField(widget=forms.Textarea({'cols': '60', 'rows': "3"}))
    # task.widget.attrs.update({'cols': '40', 'rows': "2"})

    class Meta:
        model = AlgoTask
        fields = '__all__'
        # fields = ['task', 'a', 'b','c']
        print('\nfields: ', fields)

algo_task/views.py
from django.shortcuts import render, redirect
from django.db.models import Count, Avg, Min, Max, StdDev, Sum
from .forms import CreateAbcForm
from .models import AlgoTask
from math import pi


def main(request):
    # print('request.method: ', request.method)
    if request.method == 'POST':
        form = CreateAbcForm(request.POST)
        if form.is_valid():
            # print("\nform_is_valid:\n", form)
            form.save()
            return redirect('algo_task:form_result')
    else:
        form = CreateAbcForm()
        # print('\nform_else:\n', form)
    context = {'form': form}
    #  print("\ncontext:\n", context)
    return render(request, 'main.html', context)

def form_result(request):
    object = AlgoTask.objects.all().order_by('-id')[:1]
    print("object: ", object)
    # dict
    row = object.values('A', 'H', 'R', 'M')[0]
    print("row: ", row)
    # list
    row_list = object.values_list()[0]
    print("row_list: ", row_list)
    if row['A'] ** 3 >= row['M']:
        result_1 = "Поместиться в 1 емкость"
    else:
        result_1 = "Не поместиться в 1 емкость"

    if row['R'] ** 2 * pi * row['H'] >= row['M']:
        result_2 = "поместиться во 2 емкость"
    else:
        result_2 = "не поместиться во 2 емкость"
    # context
    result = result_1 + ', ' + result_2
    task = row_list[1]
    print('task: ', task)
    last_data = [row_list[2], row_list[3], row_list[4]]
    print('last_data:', last_data)
    print('result: ', result)
    context = {'task': task, 'last_data': last_data, 'result': result, 'row': row}
    return render(request, 'form_result.html', context)


def table(request):
    row = AlgoTask.objects.values()
    print('row:', row)
    row_lists = AlgoTask.objects.values_list()
    print('row_lists:', row_lists)
    cur_objects = AlgoTask.objects.all()
    statics_val = [cur_objects.aggregate(Count('M')), cur_objects.aggregate(Avg('M')), cur_objects.aggregate(Min('M')),
                   cur_objects.aggregate(Max('M')), cur_objects.aggregate(StdDev('M')), cur_objects.aggregate(Sum('M'))]
    print(statics_val)
    statics = {'statics_val': statics_val}

    fields = AlgoTask._meta.get_fields()
    print(fields)
    verbose_name_list = []
    name_list = []
    for e in fields:
        verbose_name_list.append(e.verbose_name)
        name_list.append(e.name)
    print(verbose_name_list)
    print(name_list)
    field_names = verbose_name_list
    context = {'row': row, 'row_lists': row_lists, 'field_names': field_names, 'statics': statics}
    return render(request, 'table.html', context)

algo_task/templates/form_result.html
{% extends 'layout.html' %}

{% block title %}Алгос: результат{% endblock %}

{% block content %}
    <h5>Результат</h5>
    <h6>{{ task }}</h6>
    <table class="table table-bordered">
        <tr>
            {% for k, v in row.items %}
                <td>{{ k }}: {{ v }}</td>
            {% endfor %}
            <td>{{ result }}</td>
        </tr>
        </tbody>
    </table>
{% endblock %}

algo_task/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'css/mycss.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>

<div class="container">
    <div class="card">
        <div class="card-body">
            {% include "navigation.html" %}
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% block content %}{% endblock %}
        </div>
    </div>

</div>

<body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

algo_task/templates/main.html
{% extends 'layout.html' %}

{% block title %}Алгос: форма {% endblock %}

{% block content %}
    <h5>Создание формы</h5>
{#    {% load widget_tweaks %}#}
    <form {% url 'algo_task:main' %} method="POST">
        {% csrf_token %}
        {{ form }}
        <label for="id_submit">&nbsp;</label>
        <button type="submit" id="id_submit">Отправить</button>
        </label>
    </form>
{% endblock %}

algo_task/templates/navigation.html
<ul class="nav">
    <li class="nav-item"><a class="nav-link" href="{% url 'algo_task:main' %}">Форма</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'algo_task:form_result' %}">Результат</a></li>
    <li class="nav-item"><a class="nav-link" href="{% url 'algo_task:table' %}">Таблица</a></li>
</ul>

algo_task/templates/table.html
{% extends 'layout.html' %}

{% block title %}Алгоc: таблица{% endblock %}


{% block content %}
    <h5>Таблица</h5>
    <table class="table table-bordered">
        <tbody style="border-top: 3.0px;">
        <tr>
        {% for name in field_names%}
        <td>{{ name }}</td>
        {% endfor %}
        </tr>
        {% for items in row_lists %}
            <tr>
                {% for item in items %}
                    <td>
                        {{ item }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}
        <tbody>
    </table>

    <p>Статистика</p>
{#    {% autoescape off %}{{ statics.statics_val }}{% endautoescape %}#}
    {% for item in statics.statics_val %}
        {% for k, v in  item.items %}
            {{ k }}:  {{ v }};
{#            {% autoescape off %}{{ k }}:  {{ v }}; {% endautoescape %}#}
        {% endfor %}
    {% endfor %}


{% endblock %}